development:
  adapter: postgresql
  database: todo2
  host: localhost
  username: postgres
  password: "postgres"  #Put your password here

production:
  adapter: postgresql
  database: todo2
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000